version: "3"

services:
  api: 
    build:
      context: .
    image: sandbox-api
    ports:
      - "3000:3000"
    # tty: true
    # stdin_open: true
    command: /bin/sh -c "rm -f /rails/tmp/pids/server.pid && rails s -p 3000 -b 0.0.0.0"
    # read_only: true