# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ffb0d067bde00db4727600b3b421c19e19dee1338efd218e629bb6847c48405ae2d6b455170fb18c811f92b88b3f85d883701620fe94edb0822806841e687985

test:
  secret_key_base: 88940e32842ba4075e734b474e47a49e07cc9abf9055f90f41d53f6d407c1fb9dcb8ab00e643cae6e99537d5e65e7ff56f86d480c0cd086f9fb949d14949cb77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
